name: Upload Website Frontend code

on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read
    pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # sync to dev
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: Github-master

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://dev.davidkayode.com --delete --exclude ".git*"

      # sync to prod
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.PROD_ROLE }}
          aws-region: ${{secrets.PROD_REGION}}
          role-session-name: Github-master

      - name: Deploy static site to S3 bucket
        run: aws s3 sync . s3://davidkayode.com --delete --exclude ".git*"